### ISSUE TITLE
type and resolution of image

### ISSUE THREAD

**Issue by shubham2323** [machinalis/satimg#4]
Can you please share the source, resolution, names of bands of the image?? It wasn't mentioned anywhere in the readme too.

**Comment by cmdelatorre** [comment]
Image data includes a Geotiff file with the crop of a L1T Landsat scene (LANDSAT 8, sensor OLI, path 229, row 81, 2016-01-19 19:14:02 UTC). Only bands 1 to 7 are present (Aerosol, VIS, NIR, SWIR. 30m resolution).

It was mentioned in the original blog post, which unfortunately is down :-( I kinda recovered it here: http://machinalis32.rssing.com/chan-67888834/all_p2.html#item32

Hope it helps
