### ISSUE TITLE
Why did you remove the blog?

### ISSUE THREAD

**Issue by LuizGC** [machinalis/satimg#5]
Can I read the full explanation in other place?

http://www.machinalis.com/blog/python-for-geospatial-data-processing/

**Comment by cmdelatorre** [comment]
Hi there. Machinalis was acquired by Mercadolibre. In the merge, some artifacts (such as the blog) were lost.

There's a version of the post you are looking for, here: http://machinalis8.rssing.com/chan-51920729/latest.php#item3
